Added workflow instance and bulk cancellation to the UI
elsa-workflows/elsa-studio pull request #148
Opened 2024-02-19 15:18 UTC by raymonddenhaan

With this change it is possible to cancel a single workflow, select a number of workflows to cancel and cancel all instances of a definition from the UI.

Dependent on this PR from Elsa-core:
https://github.com/elsa-workflows/elsa-core/pull/4965

2024-02-19 15:20 UTC, raymonddenhaan commented
Need to update Elsa-core package after the dependent PR is merged

2024-02-26 13:13 UTC, sfmskywalker requested changes

2024-02-26 13:13 UTC, sfmskywalker commented on src/modules/Elsa.Studio.Workflows/Components/WorkflowDefinitionList/WorkflowDefinitionList.razor.cs
> +            "Are you sure you want to cancel all running workflow instance of this workflow definition?", yesText: "Yes", cancelText: "No");
Small typo: should be: "workflow instances" (notice plural form).

2024-02-26 13:21 UTC, sfmskywalker approved these changes

2024-02-26 13:21 UTC, merged